USE MienMieApp;

CREATE TABLE IF NOT EXISTS mm_user_account (
  user_id VARCHAR(64) NOT NULL PRIMARY KEY,
  phone VARCHAR(32) NOT NULL,
  password VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
