USE MienMieApp;

CREATE TABLE IF NOT EXISTS mm_job_position (
  position_id VARCHAR(64) NOT NULL PRIMARY KEY,
  space_id VARCHAR(64) NOT NULL,
  title VARCHAR(256) NOT NULL,
  company VARCHAR(256) NOT NULL DEFAULT '',
  location VARCHAR(256) NOT NULL DEFAULT '',
  base_range VARCHAR(8000) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
